### ISSUE TITLE
Few issues on compiling the program on MacOSX

### ISSUE THREAD

**Issue by hgeorge21** [alecjacobson/computer-graphics-bounding-volume-hierarchy#36]
1. Runs into error when compiling with GCC, seems to only work with Clang
2. Does not seem to have Eigen included, cannot seem to link it...

**Comment by abhimadan** [comment]
You have to use `git clone --recursive` for this assignment, since Eigen is included as a submodule of libigl, which is the only direct submodule on this assignment. Since you've already cloned, use `git submodule update --init --recursive` instead.

**Comment by abhimadan** [comment]
I'll reopen this since I'm sure others will have this issue and leaving it open improves visibility.

**Comment by hgeorge21** [comment]
I re-cloned it and after trying to compile it here is the issue...

![Screen Shot 2019-10-02 at 8 23 32 PM](https://user-images.githubusercontent.com/16624758/66090700-843a4100-e552-11e9-8ba0-644551242ea7.png)

**Comment by abhimadan** [comment]
Thanks for pointing this out. I've pushed a fix, so it should work if you pull the latest version of the repo.

**Comment by aiwen324** [comment]
I still cannot find even after `git submodule update --init --recursive`. 
Also tried `find ./ -name "*igen"` after update but get nothing either.

**Comment by abhimadan** [comment]
Do you see the libigl directory? If you do, then Eigen should be located at `computer-graphics-bounding-volume-hierarchy/libigl/external/eigen`.

**Comment by aiwen324** [comment]
I didn't see external folder inside libigl. Even on the github repo for libigl at header [230df4d](https://github.com/libigl/libigl/tree/230df4d30b46ef4b7cd6ab68eb1c7e83cad7e09a). I cannot find external folder either.

**Comment by abhimadan** [comment]
It turns out that Eigen is not a submodule of libigl, but instead it downloads Eigen through its CMake config. Our CMake file is configured to build libigl as well, so if you follow the usual cmake instructions from this repo, it will build libigl, which will in turn download Eigen.

**Comment by aiwen324** [comment]
Great, it works now! Thanks! Didn't know you can download the module with cmake, that's neat.
